---

- name: create operator token
  when:
    - not running_in_check_mode
  bodsch.influx.influxdb3_token:
    version: "{{ influxdb_version }}"
    host: "{{ influxdb_http }}"
    auth_enabled: "{{ influxdb_service.auth.enabled | default(false) | bool }}"
    token_file: "{{ influxdb_config_dir }}/operator.token"
  register: _operator

- name: ensure databases exist
  when:
    - not running_in_check_mode
    - influxdb_databases | default({}) | length > 0
  bodsch.influx.influxdb3_database:
    host: "{{ influxdb_http }}"
    token: "{{ _operator.token | default(omit) }}"
    databases: "{{ influxdb_databases }}"
  register: _databases

...
