---

- name: set influxdb default user, organization, and bucket
  when:
    - not running_in_check_mode
    - influxdb_main_version | int == 2
  bodsch.influx.influxdb2_setup:
    host: "{{ influxdb_http }}"
    org: "{{ influxdb_primary.organization }}"
    bucket: "{{ influxdb_primary.bucket }}"
    username: "{{ influxdb_primary.username }}"
    password: "{{ influxdb_primary.password }}"
    token: "{{ influxdb_primary.token }}"
  register: _setup

- name: ensure organizations exists
  when:
    - not running_in_check_mode
    - influxdb_main_version | int == 2
  bodsch.influx.influxdb2_organizations:
    host: "{{ influxdb_http }}"
    token: "{{ influxdb_primary.token }}"
    organizations: "{{ influxdb_organizations }}"
  register: _org

- name: ensure users exist
  when:
    - not running_in_check_mode
    - influxdb_main_version | int == 2
  bodsch.influx.influxdb2_users:
    host: "{{ influxdb_http }}"
    token: "{{ influxdb_primary.token }}"
    users: "{{ influxdb_users }}"
  register: _users

- name: ensure buckets exist
  when:
    - not running_in_check_mode
    - influxdb_main_version | int == 2
  bodsch.influx.influxdb2_buckets:
    host: "{{ influxdb_http }}"
    token: "{{ influxdb_primary.token }}"
    buckets: "{{ influxdb_buckets }}"
  register: _buckets

...
