---

- name: define influxdb http service
  ansible.builtin.set_fact:
    influxdb3_http: "{{ influxdb3_service.http | bodsch.influx.influxdb_bind(core_version=influxdb3_main_version) }}"

# - name: create influxdb config directory
#   when:
#     - not running_in_check_mode
#   ansible.builtin.file:
#     path: "{{ influxdb3_config_dir }}"
#     state: directory
#     owner: "{{ influxdb3_system_user }}"
#     group: root
#     mode: "0755"
#
# - name: create influxdb configuration
#   when:
#     - not running_in_check_mode
#   ansible.builtin.template:
#     src: etc/influxdb/config.yml.j2
#     dest: "{{ influxdb3_config_dir }}/config.yml"
#     owner: root
#     group: "{{ influxdb3_system_group }}"
#     mode: "0644"
#   notify:
#     - restart influxdb3

- name: ensure influxdb3 is started
  when:
    - not running_in_check_mode
  become: true
  ansible.builtin.service:
    name: influxdb3
    state: started

- name: ensure influxdb 3 is up and running
  when:
    - not running_in_check_mode
  bodsch.influx.influxdb3_ping:
    host: "{{ influxdb3_http }}"
  retries: 10
  delay: 5
  register: _ping
  until: _ping.reachable
  changed_when: false

# - name: influxdb3
#   when:
#     - not running_in_check_mode
#   ansible.builtin.include_tasks: configure/influxdb3.yml

...
