---

# see: https://docs.influxdata.com/influxdb/v2/reference/release-notes/influxdb/
influxdb3_version: "3.0.0"

influxdb3_scm:
  use_tags: false
  without_beta: true
  version_filter:
    - ".*test*"
    - ".*preview"
    - ".*beta"
    - ".*rc"

influxdb3_release: {}
  # download_url: ""
  # api_url: ""
  # files:
  #   influxdb: ""
  #   influx_client: ""
  # binaries:
  #   influxd: ""
  #   influx: ""

influxdb3_system_user: influxdb
influxdb3_system_group: influxdb
influxdb3_config_dir: /etc/influxdb3
influxdb3_storage_dir: /var/lib/influxdb3

influxdb3_direct_download: false

influxdb3_serve: {}

influxdb3_config:
  http-bind-address: 127.0.0.1:8086
  reporting-disabled: true

influxdb3_primary:
  organization: example-org
  bucket: example-bucket
  username: example-user
  password: LA9NMTb6WZ285zPGPgyUJEucuJUjr6W7
  token: example-token

influxdb3_organizations: {}

influxdb3_users: {}

influxdb3_buckets: {}

# InfluxDB 3 native databases (only used when influxdb3_main_version == 3)
influxdb3_databases: {}

...
