---

influxdb3_main_version: "{{ influxdb3_version[0:1] }}"

influxdb3_bin_version: "influxdb{{ influxdb3_main_version if influxdb3_main_version | int == 2 else '' }}"

influxdb3_install_path: /opt/influxdb/{{ influxdb3_version }}

influxdb3_install_paths:
  core: /opt/influxd/{{ influxdb3_version }}
  client: /opt/influx/{{ influxdb3_cli_version }}

influxdb3_delegate_to: localhost

influxdb3_local_tmp_directory: "{{
  lookup('env', 'CUSTOM_LOCAL_TMP_DIRECTORY') |
  default(lookup('env', 'HOME') ~ '/.cache/ansible/influxdb', true) }}/{{ influxdb3_version }}"

influxdb3_dependencies:
  - python3-requests

influxdb3_defaults_serve:
  # Node identifier used as prefix in object store file paths
  node_id: "{{ ansible_facts.hostname }}"

  # common-options
  http:
    # v3 - Address for HTTP API requests [default: 0.0.0.0:8181]
    bind: "127.0.0.1:8181"

  log:
    # v3 -
    filter: "info"
    # v3 -
    format: "full"
    # v3 -
    destination: "stdout"

  auth:
    # Run InfluxDB 3 server without authorization
    enabled: false

  metrics:
    # v2 - Don't expose metrics over HTTP at /metrics
    enabled: true



# ----------------------------------------------------------------------------------------

influxdb3_defaults_directory: /etc/default

# Version 1
# https://download.influxdata.com/influxdb/releases/influxdb-1.11.8-linux-amd64.tar.gz

# Version 2
# https://download.influxdata.com/influxdb/releases/v2.7.12/influxdb2-2.7.12_linux_amd64.tar.gz
# https://dl.influxdata.com/influxdb/releases/influxdb2-client-2.7.5-linux-amd64.tar.gz

# Version 3
# https://dl.influxdata.com/influxdb/releases/influxdb3-${EDITION_TAG}-${INFLUXDB_VERSION}_${ARTIFACT}.tar.gz"
# https://dl.influxdata.com/influxdb/releases/influxdb3-core-3.0.0_linux_amd64.tar.gz
# https://dl.influxdata.com/influxctl/releases/influxctl-v2.10.3-linux-x86_64.tar.gz

influxdb3_defaults_release:
  download_urls:
    core: "https://dl.influxdata.com/influxdb/releases"
    client: "https://dl.influxdata.com/influxdb/releases"
  api_url: ""
  files:
    influxdb: "{{ influxdb3_bin_version }}-{{ influxdb3_version }}-{{ ansible_facts.system | lower }}-{{ system_architecture }}.tar.gz"
    influx_client: "{{ influxdb3_bin_version }}-client-{{ influxdb3_cli_version }}-{{ ansible_facts.system | lower }}-{{ system_architecture }}.tar.gz"
  binaries:
    influxd: "influxd"
    influx: "influx"

# ------------------------------------------------------------------------

go_arch_map:
  x86_64: 'amd64'
  aarch64: 'arm64'

system_architecture: "{{ go_arch_map[ansible_facts.architecture] | default(ansible_facts.architecture) }}"

systemd_lib_directory: /lib/systemd/system

...
