---

influxdb2_version: "2.9.1"

# influxdb2_cli_version: "2.7.1"

influxdb2_service:
  # supported log levels are debug, info, and error (default info)
  log:
    level: debug
  ui:
    enabled: true
  http:
    # bind address for the REST HTTP API (default ":8086")
    bind_address: "{{ ansible_facts.default_ipv4.address }}:8086"

influxdb2_organizations:
  main-org:
    state: create
    description: Main organization
  guest-org:
    state: create

influxdb2_users:
  admin:
    state: create
    operator: false
    organization:
      name: main-org
      admin: true
    password: LA9NMTb6WZ285zPGPgyUJEucuJUjr6W7

  admin01:
    state: create
    organization:
      name: main-org
    password: secretPassword
    permissions: []

  guest01:
    state: create
    organization:
      name: guest-org
    password: secretPassword

influxdb2_buckets:
  bucket01:
    state: create
    description: First bucket
    organization:
      name: main-org
    retention: 1d
  bucket02:
    description: Second bucket
    organization:
      name: main-org

...
