---

- name: systemd daemon reload
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    force: true
  when:
    - ansible_facts.service_mgr | lower == "systemd"

- name: start influxdb2
  ansible.builtin.service:
    name: influxdb2
    state: started

- name: restart influxdb2
  ansible.builtin.service:
    name: influxdb2
    state: restarted

- name: reload influxdb2
  ansible.builtin.service:
    name: influxdb2
    state: reloaded

...
